### ISSUE TITLE
スクレイピングが途中で終了してしまう

### ISSUE THREAD

**Issue by kakerururu** [Mkamono/box-over-looker#16]
現状まとめメモ
PRoductの最後の商品のrakumaで発生した
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/7559f5cf-ff84-49bd-8617-337bbc2d447d)

・SCのログ
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/7a737b4b-f3b6-42ba-a2a3-3009ac549cfe)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/4b116886-5caf-4039-a176-3a9dfd2f15f4)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/08480a85-6665-41ae-9d95-1eb8aaab9bc8)

発生したエラーの原因メモ
・URLが存在していない
https://note.com/motchalini/n/n380b27fe1090
・短時間に同じIPアドレスから多くのリクエストを送信した場合、サーバから接続拒否される場合

とりあえずurlが存在するか検証

**Comment by kakerururu** [comment]
&excluded_query=&min=1000&max=1000000&transaction=selling&sort=sell_price&order=asc&page=5

**Comment by kakerururu** [comment]
検証
ページ遷移するたびにログ出力、rakumanのみに絞って定期実行してみる（5分間隔ぐらい）

**Comment by kakerururu** [comment]
次やることメモ
driver.getをリトライする

**Comment by kakerururu** [comment]
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/a23f2e70-4abb-4b7d-9015-802b9cac011c)

**Comment by kakerururu** [comment]
エラー箇所発覚
ステータスコードのGET
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/62e387fe-4a49-4130-9133-b64dfb2b0732)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/7ce18c16-b4f6-423c-a8c0-e1ca9da43b84)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/b3837e03-92e8-4620-bbe1-bf5c9d27ca43)

**Comment by Mkamono** [comment]
動的サイトと同様にレスポンスだとうまくいかないし、エラーの再現性が低いというデメリットを鑑みると、時間の短縮というメリットを上回ると判断してdriverでのチェックに切り替えるのはアリ

**Comment by Mkamono** [comment]
比較検討の上での出戻りはいいんですよ。思いつきでやろうとするのがヤバそうなだけで
