### ISSUE TITLE
メール関連

### ISSUE THREAD

**Issue by kakerururu** [Mkamono/box-over-looker#17]
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/d6b1bfce-663e-4a7e-8720-c16b7354f3fe)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/5879c81b-9d10-4fb2-91f5-0dc8868c744a)

**Comment by Mkamono** [comment]
このメンバってなんですか？
何の有無を表すbool？

**Comment by kakerururu** [comment]
> このメンバってなんですか？ 何の有無を表すbool？

BEのREAD＆諸々の計算で、各商品ごとの変動を検知
→PriceChangeクラスで、変動があったものをtrueに変更。
Trueがあれば、変更したクラスをそのままPOST
全部Falseなら特にPOSTしない
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/d9bbf23d-3ad4-49c7-b10d-cfa080a0906a)

**Comment by kakerururu** [comment]
FASTAPI使えないからBaseModel使えないな......

**Comment by kakerururu** [comment]
現状の指摘
・今のままだと、BEとの依存関係が強くなってしまっている。
（Priceクラスをflaskのところに送ってしまう時点で、flask側で処理する必要性が出てる）

解決案
・flaskはメールの本文と宛先等をPOSTで受け取り次第、その内容をメール送信するだけ、って考えたほうが良い。
→BEでメールの本文を作成してしまえば、各サーバーの役割がはっきりする
