### ISSUE TITLE
メールサーバーの構成

### ISSUE THREAD

**Issue by kakerururu** [Mkamono/box-over-looker#21]
エンドポイントで行う動作
・SMTPサーバーへのログイン
・POSＴされた内容をメール送信関数に渡す
の2点

メール送信について
メール送信に必要なモノ
・コネクションの作成
・ＰＯＳＴされた内容をメール本文に格納（関数化しなくてもできるかも？）

**Comment by kakerururu** [comment]
BEの完成形
・Mailクラスを埋めるためにbody作成関数を作る
・クラスメソッドでjsonに変換してflaskにポスト
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/ee9f93c3-7ec0-40d7-9c07-5a63bd1231f9)

**Comment by kakerururu** [comment]
メールサーバーメモ
キーが存在しないときはエラーを吐く

**Comment by kakerururu** [comment]
jsonでのデータの受け渡しはイケルの確認
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/5f1f24ee-d85b-44c2-b667-08e8fa3c7979)
![image](https://github.com/Mkamono/box-over-looker/assets/144202943/e7c57141-4729-4606-a159-45353640b678)

**Comment by kakerururu** [comment]
> BEでやってjson吐き出すならbasemodel使えばいいと思うよ

返信急に表示されてビビった～
BasemodelってFASTAPI同士でやるときはマッピングとかできる恩恵が付いてくるけど、jsonのやり取りするだけだったら採用してもいいんか

**Comment by Mkamono** [comment]
BEはFastAPIで立ってるでしょ? だからダイジョブ
